name: Build & Push Docker Image

on:
  repository_dispatch:
    types: [ timetracking-updated ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout timetracking-docker
        uses: actions/checkout@v4

      - name: Clone timetracking (private repo)
        run: git clone https://${{ secrets.GITHUB_TOKEN_PRIVATE_REPO }}@github.com/c0rrre/timetracking.git ./timetracking

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/timetracking-docker
          echo "Building image: $IMAGE:latest"
          docker build -t $IMAGE:latest ./timetracking
          docker push $IMAGE:latest
